[package]
name = "sprockets"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "0.29.0"
redis = "0.8.0"
sqlx = "0.8.6"
tokio = { version = "1.46.1", features = ["full"] }

